function [fitresult, gof, output] = fcn_createFit(struct,handles,options)
%CREATEFIT(WN_7CSSP0,SIG_7CSSP0)
%  Create a fit.
%
%  Data for '7Cssp0' fit:
%      X Input : wn_7Cssp0
%      Y Output: sig_7Cssp0
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 25-Aug-2014 16:22:59

%% Extract CellData
x = struct.wn;
y = struct.signal;

%% Damping Coefficients
G = options.G;
% Bounds
dG = options.dG;

%% Peak Positions
w = options.w;
% Bounds
dw = options.dw;

%% Non Resonant Signal
% Slope
m = -0.0045;
c = w(numel(w)) * abs(m);
c = 5;
% Bounds
dc = inf;

%% Oscillator Strengths
A = zeros(1,length(w));
i = 1;

% Create dummy weights array
opts.Weights = ones(1,length(x));

while i <= numel(A)
    % Find index number of each Start Point of the peak frequencies
    [delta, idx] = min(abs(x - w(i)));
    % If peak location is not in range make the index num the max idx of x
    if w(i) > (max(x) - dw)
        [value, idx] = max(x);
        idx = idx + dw;
    end
    % Get the values around the Start Point for each peak
    k = ceil(-dw/2);
    n = 1;
    while k <= dw/2
        yVals(n) = y(idx + k);
        k = k + 1;
        n = n + 1;
    end
    % Get the maximum Value and Idex of the y values around the peak position
    [yValsMax, yIdxMax] = max(yVals);
    % Weight the indices around the maximum value of the peak area
    % Number of weighted data point
    nwdp = 1;
    % Weight
    wgt = 10;
    for q=(-nwdp):nwdp
        opts.Weights(idx+q) = wgt;
    end
    % Make a guess for A(i)
    DC = G(i);
    NR = m*x(idx) + c;
    % A(i) = -228.7 + 2.936*yValsMax + 48.41*DC - 0.006983*yValsMax^2 - 0.1827*yValsMax*DC - 2.64*DC^2;
    A(i) = ((yValsMax - 20*NR)/2 * DC/2)/6;
    i = i + 1;
end


%% Fit.
[xData, yData] = prepareCurveData( x, y );

% Set up fittype and options.
ft = options.ft;
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Robust = 'Bisquare';
opts.StartPoint = ...
    [A ...
    G ...
    c m ...
    w];
opts.Lower = ...
    [(ones(1,length(w)).*(-Inf)) ...
    G-dG ...
    0 -0.05 ...
    w-dw];
opts.Upper = ...
    [(ones(1,length(w)).*Inf) ...
    G+dG ...
    c+dc 0 ...
    w+dw];

opts.MaxIter = 10000;
opts.MaxFunEvals = 30000;
opts.TolFun = 10e-10;

%% Fit model to data.
[fitresult, gof, output] = fit( xData, yData, ft, opts );

%% Plot fit with data.
% Plot Data
axes(handles.axes_prev)
plot(handles.axes_prev,xData,yData,'.b')
hold on
% Plot Fit
plot(fitresult,'r')
% Options
scr_plotOptions
hold off

%% Export
fcn_dataExport(xData,yData,fitresult,options)



end