function ImportData = fcn_import

[filename,pathname] = uigetfile('*.sfg','SFG-File');

ImportData = fcn_importfile(filename,pathname);

fprintf(['Imported File: ',filename,'\n'])


function [ImportData] = fcn_importfile(filename, pathname, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as column vectors.
%   [WN,SIG1,SIG2,SIG3,SIG4] = IMPORTFILE(FILENAME) Reads data from text
%   file FILENAME for the default selection.
%
%   [WN,SIG1,SIG2,SIG3,SIG4] = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads
%   data from rows STARTROW through ENDROW of text file FILENAME.
%
% Example:
%   [wn,sig1,sig2,sig3,sig4] = importfile('Beier_7B_ppp_0°.sfg',1, 150);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2014/08/24 02:58:48

%% Initialize variables.
delimiter = '\t';
if nargin<=3
    startRow = 1;
    endRow = inf;
end

%% Format string for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen([pathname,filename],'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(1)-1, 'ReturnOnError', false);
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(block)-1, 'ReturnOnError', false);
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
wn = dataArray{:, 1};
sig1 = dataArray{:, 2};
sig2 = dataArray{:, 3};
sig3 = dataArray{:, 4};
sig4 = dataArray{:, 5};

%% Put arrays into cell Array
ImportData = {wn,sig1,sig2,sig3,sig4};

